# Generated by Django 3.0.8 on 2022-08-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menusystem", "0002_auto_20220804_2009"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("menus", models.ManyToManyField(to="menusystem.Menu")),
            ],
        ),
    ]
