# Generated by Django 3.0.8 on 2022-08-05 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menusystem", "0003_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="menus",
            field=models.ManyToManyField(related_name="meals", to="menusystem.Menu"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(help_text="YYYY-mm-dd format", unique=True),
        ),
        migrations.CreateModel(
            name="MealOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emplyee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menusystem.Meal",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menusystem.Menu",
                    ),
                ),
            ],
        ),
    ]
