# Generated by Django 3.0.8 on 2022-08-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menusystem', '0004_auto_20220805_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealorder',
            old_name='emplyee',
            new_name='employee',
        ),
    ]
