# Generated by Django 3.0.8 on 2022-08-06 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menusystem", "0005_auto_20220805_2108"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mealorder",
            unique_together={("menu", "employee")},
        ),
    ]
