# Generated by Django 3.0.8 on 2022-08-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menusystem", "0006_auto_20220806_1842"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealorder",
            name="customization",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
